name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
        DATABASE_NAME: ${{ secrets.MYSQL_DB }}
        DATABASE_USER: ${{ secrets.MYSQL_USER }}
        DATABASE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 3306
        DJANGO_SETTINGS_MODULE: messaging_app.settings

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd messaging_app
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install mysqlclient flake8 coverage pytest pytest-cov

    - name: Run migrations
      run: |
        cd messaging_app
        python manage.py makemigrations
        python manage.py migrate
      env:
        DATABASE_URL: mysql://test_user:test_password@localhost:3306/test_db
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Run tests
      run: |
        cd messaging_app
        python manage.py test --noinput --verbosity=2
      env:
        DATABASE_URL: mysql://test_user:test_password@localhost:3306/test_db
        SECRET_KEY: ${{ secrets.SECRET_KEY }}