version: '3.8'

services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: messaging_app_db
      POSTGRES_USER: messaging_user
      POSTGRES_PASSWORD: messaging_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U messaging_user -d messaging_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - DB_NAME=messaging_app_db
      - DB_USER=messaging_user
      - DB_PASSWORD=messaging_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
  media_volume: